"use client";
import {useMemo,useState} from "react";
type Step="cleanse"|"treat"|"hydrate";
type P={rank:number;brand:string;product:string;platform:string;price:number;size:number;ppo:number;velocity:string;signal:string;micro:boolean;microType?:string;bsr?:number;asin?:string;url:string;confidence:"High"|"Medium"};
const cleanse:P[]=[
{rank:1,brand:"Prequel",product:"Gleanser",platform:"TikTok Shop",price:22,size:13.5,ppo:1.63,velocity:"56.5K sold",signal:"50% glycerin; face + body value",micro:false,url:"https://shop.tiktok.com/us/k/gleanser-prequel",confidence:"High"},
{rank:2,brand:"CeraVe",product:"Hydrating Facial Cleanser",platform:"Amazon",price:15.97,size:16,ppo:1,velocity:"BSR ↑ 13 vs W01; price +11%",signal:"Ceramide mass anchor",micro:false,bsr:37,asin:"B01MSSDEPK",url:"https://www.amazon.com/dp/B01MSSDEPK",confidence:"High"},
{rank:3,brand:"Vanicream",product:"Gentle Facial Cleanser",platform:"Amazon",price:9.97,size:8,ppo:1.25,velocity:"BSR ↑ 9 vs W01",signal:"Sensitive-skin trust",micro:false,bsr:29,asin:"B00QY1XZ4W",url:"https://www.amazon.com/dp/B00QY1XZ4W",confidence:"High"},
{rank:4,brand:"La Roche-Posay",product:"Toleriane Hydrating Gentle",platform:"Amazon",price:19.97,size:13.52,ppo:1.48,velocity:"BSR ↓ 47 vs W01",signal:"Prebiotic water + ceramide",micro:true,microType:"Prebiotic",bsr:134,asin:"B01N7T7JKJ",url:"https://www.amazon.com/dp/B01N7T7JKJ",confidence:"High"},
{rank:5,brand:"BYOMA",product:"Creamy Jelly Cleanser",platform:"Cross-platform",price:11.49,size:5.91,ppo:1.94,velocity:"TikTok-native",signal:"Tri-ceramide; visual codes",micro:false,url:"https://shop.tiktok.com/us/pdp/creamy-jelly-cleanser-byoma-for-hydration-skin-barrier-repair/1731151872467439664",confidence:"Medium"},
{rank:6,brand:"Naturium",product:"Niacinamide Cleansing Gelée",platform:"TikTok Shop",price:17.9,size:7.1,ppo:2.52,velocity:"326 sold",signal:"Active-led non-stripping",micro:false,url:"https://shop.tiktok.com/us/pdp/niacinamide-cleansing-gelee-3-by-naturium-for-soft-smooth-skin/1729776876934828438",confidence:"High"},
{rank:7,brand:"KraveBeauty",product:"Matcha Hemp Hydrating",platform:"Amazon",price:16,size:4.05,ppo:3.95,velocity:"BSR ↓ 533 vs W01",signal:"K-beauty sensoriality",micro:false,bsr:8095,asin:"B0BZ9KMY3S",url:"https://www.amazon.com/dp/B0BZ9KMY3S",confidence:"High"},
{rank:8,brand:"BeautyStat",product:"Microbiome Barrier Balancing",platform:"TikTok Shop",price:13,size:4,ppo:3.25,velocity:"194 product sold; shop 24.9K",signal:"Direct microbiome proposition",micro:true,microType:"Microbiome",url:"https://shop.tiktok.com/us/pdp/cleanser-beautystat-universal-microbiome-barrier-150ml-hydrates-protects/1729414753674367088",confidence:"High"},
{rank:9,brand:"Aveeno",product:"Calm + Restore Oat",platform:"Cross-platform",price:11.99,size:7.8,ppo:1.54,velocity:"Mass/editorial",signal:"Oat comfort cue",micro:false,url:"https://www.ulta.com/p/calm-restore-nourishing-oat-facial-cleanser-pimprod2017040",confidence:"Medium"},
{rank:10,brand:"ROUND LAB",product:"1025 Dokdo Cleanser",platform:"Amazon",price:11.39,size:5.07,ppo:2.25,velocity:"1,761 ratings",signal:"Low-pH K-beauty",micro:false,url:"https://www.amazon.com/s?k=ROUND+LAB+1025+Dokdo+Cleanser",confidence:"Medium"},
{rank:11,brand:"Skinfix",product:"Ceramide + Ectoin Gentle Gel",platform:"Cross-platform",price:30,size:6,ppo:5,velocity:"Community chatter",signal:"Clinical-premium",micro:false,url:"https://skinfix.com/products/barrier-ectoin-ceramide-gentle-gel-cleanser",confidence:"Medium"},
{rank:12,brand:"ETUDE",product:"SoonJung pH 6.5 Whip",platform:"Amazon",price:13,size:5.06,ppo:2.57,velocity:"Deal visibility",signal:"Low-pH sensitive foam",micro:false,url:"https://www.amazon.com/s?k=ETUDE+SoonJung+pH+6.5+Whip",confidence:"Medium"},
{rank:13,brand:"Cetaphil",product:"Gentle Skin Cleanser",platform:"Amazon",price:14.47,size:20,ppo:.72,velocity:"Mass evergreen",signal:"Lowest unit-cost anchor",micro:false,url:"https://www.amazon.com/s?k=Cetaphil+Gentle+Skin+Cleanser+20+oz",confidence:"Medium"},
{rank:14,brand:"The Ordinary",product:"Glycolipid Cream Cleanser",platform:"Cross-platform",price:12.5,size:5,ppo:2.5,velocity:"Strong search",signal:"Clinical value",micro:false,url:"https://theordinary.com/en-us/glycolipid-cream-face-cleanser-100615.html",confidence:"Medium"},
{rank:15,brand:"Eucerin",product:"Hydrating Cleansing Gel",platform:"Amazon",price:10.99,size:6.8,ppo:1.62,velocity:"Derm/mass",signal:"HA hydration value",micro:false,url:"https://www.amazon.com/s?k=Eucerin+Hydrating+Cleansing+Gel",confidence:"Medium"}];
const treat:P[]=[
{rank:1,brand:"Cocokind",product:"Ceramide Barrier Serum",platform:"TikTok Shop",price:20.6,size:1,ppo:20.6,velocity:"498 sold",signal:"21% promo; accessible ceramides",micro:false,url:"https://shop.tiktok.com/us/k/barrier-serums",confidence:"High"},
{rank:2,brand:"The Ordinary",product:"Soothing & Barrier Support Serum",platform:"Cross-platform",price:17.5,size:1,ppo:17.5,velocity:"High search/social",signal:"Pink formula; mass clinical",micro:false,url:"https://theordinary.com/en-us/soothing-barrier-support-serum-100634.html",confidence:"High"},
{rank:3,brand:"KraveBeauty",product:"Great Barrier Relief",platform:"Cross-platform",price:28,size:1.52,ppo:18.42,velocity:"Cult/community",signal:"Tamanu + oil-serum format",micro:false,url:"https://kravebeauty.com/products/great-barrier-relief",confidence:"High"},
{rank:4,brand:"Prequel",product:"Multi-Quench Plumping Serum",platform:"TikTok Shop",price:28,size:1.7,ppo:16.47,velocity:"Brand: 631K shop sold",signal:"Large-format hydration treatment",micro:false,url:"https://shop.tiktok.com/us/k/prequel-multi-quench-serum",confidence:"Medium"},
{rank:5,brand:"Experiment",product:"Super Saturated",platform:"Cross-platform",price:28,size:1,ppo:28,velocity:"Creator/derm momentum",signal:"30% glycerin named story",micro:false,url:"https://experimentbeauty.com/products/super-saturated",confidence:"Medium"},
{rank:6,brand:"Naturium",product:"Barrier Bounce",platform:"Cross-platform",price:25,size:1.7,ppo:14.71,velocity:"Retail/social momentum",signal:"Peptide + squalane emulsion",micro:false,url:"https://naturium.com/products/barrier-bounce",confidence:"Medium"},
{rank:7,brand:"The INKEY List",product:"Ectoin Hydro-Barrier Serum",platform:"Cross-platform",price:15,size:1,ppo:15,velocity:"Ingredient momentum",signal:"Ectoin value challenger",micro:false,url:"https://www.theinkeylist.com/products/ectoin-hydro-barrier-serum",confidence:"Medium"},
{rank:8,brand:"Murad",product:"Biome-Balancing Clear & Prevent",platform:"TikTok Shop",price:71,size:1,ppo:71,velocity:"1.2K sold",signal:"Biome-sensing tech + acne actives",micro:true,microType:"Biome-sensing",url:"https://shop.tiktok.com/us/pdp/biome-balancing-acne-serum-by-murad-clears-breakouts-fast-non-comedogenic-formula-supports-healthy-s/1731001908607488040",confidence:"High"},
{rank:9,brand:"U Beauty",product:"Barrier Bioactive Mist",platform:"Cross-platform",price:78,size:3.38,ppo:23.08,velocity:"2026 editorial breakout",signal:"Postbiotic serum-mist",micro:true,microType:"Postbiotic",url:"https://www.ubeauty.com/products/the-barrier-bioactive-treatment",confidence:"High"},
{rank:10,brand:"BYOMA",product:"Hydrating Serum",platform:"Cross-platform",price:16,size:1.01,ppo:15.84,velocity:"TikTok-native",signal:"Tri-ceramide mass serum",micro:false,url:"https://byoma.com/products/hydrating-serum",confidence:"Medium"},
{rank:11,brand:"Glow Recipe",product:"Avocado Ceramide Recovery",platform:"Cross-platform",price:45,size:1,ppo:45,velocity:"Prestige social",signal:"Redness/barrier desire hook",micro:false,url:"https://www.glowrecipe.com/products/avocado-ceramide-recovery-serum",confidence:"Medium"},
{rank:12,brand:"Skinfix",product:"Triple Lipid + Collagen Serum",platform:"Cross-platform",price:52,size:1,ppo:52,velocity:"Clinical prestige",signal:"Lipid replenishment",micro:false,url:"https://skinfix.com/collections/serums",confidence:"Medium"},
{rank:13,brand:"Gallinée",product:"Youthful Serum",platform:"Cross-platform",price:45,size:1,ppo:45,velocity:"Microbiome niche",signal:"Prebiotic + postbiotic language",micro:true,microType:"Pre/Postbiotic",url:"https://www.gallinee.com/collections/face",confidence:"Medium"},
{rank:14,brand:"Roe Wellness",product:"Probiotic Power Serum",platform:"TikTok Shop",price:32,size:1,ppo:32,velocity:"18 set sales",signal:"Family/kids biome positioning",micro:true,microType:"Probiotic",url:"https://shop.tiktok.com/us/pdp/probiotic-power-serum-biome-barrier-cream-set-by-roe-wellness-for-kids/1729943833416536620",confidence:"Medium"},
{rank:15,brand:"Kat Burki",product:"VitaBiome Active Skin Optimizer",platform:"Cross-platform",price:75,size:3.4,ppo:22.06,velocity:"2026 award/editorial",signal:"Biome sequencing proof story",micro:true,microType:"Pre/Pro/Postbiotic",url:"https://www.katburki.com",confidence:"Medium"}];
const hydrate:P[]=[
{rank:1,brand:"ILLIYOON",product:"Ceramide Ato Concentrate Cream",platform:"TikTok Shop",price:15.82,size:6.76,ppo:2.34,velocity:"53K sold",signal:"K-beauty value + 100h claim",micro:false,url:"https://shop.tiktok.com/us/k/moisturizers-to-help-skin-barrier",confidence:"High"},
{rank:2,brand:"Purito",product:"Mighty Bamboo Panthenol Cream",platform:"TikTok Shop",price:23,size:3.38,ppo:6.8,velocity:"11.2K sold",signal:"10% panthenol; recovery",micro:false,url:"https://shop.tiktok.com/us/k/moisturizers-to-help-skin-barrier",confidence:"High"},
{rank:3,brand:"Dr. Althea",product:"345 Relief Cream",platform:"TikTok Shop",price:28.29,size:1.69,ppo:16.74,velocity:"40.4K sold",signal:"K-beauty viral recovery",micro:false,url:"https://shop.tiktok.com/us/k/moisturizers-to-help-skin-barrier",confidence:"High"},
{rank:4,brand:"CeraVe",product:"Moisturizing Cream",platform:"Amazon",price:17.98,size:19,ppo:.95,velocity:"Mass leader",signal:"Ceramide value floor",micro:false,url:"https://www.amazon.com/s?k=CeraVe+Moisturizing+Cream+19+oz",confidence:"High"},
{rank:5,brand:"La Roche-Posay",product:"Cicaplast Balm B5+",platform:"Cross-platform",price:18.99,size:1.35,ppo:14.07,velocity:"Hero repair product",signal:"Tribioma prebiotic complex",micro:true,microType:"Prebiotic",url:"https://www.laroche-posay.us/our-products/face/face-moisturizer/cicaplast-balm-b5-for-dry-skin-irritations-3337872412998.html",confidence:"High"},
{rank:6,brand:"Tower 28",product:"SOS Barrier Recovery Cream",platform:"TikTok Shop",price:26.66,size:1.86,ppo:14.33,velocity:"257 sold",signal:"Sensitive-skin social proof",micro:false,url:"https://shop.tiktok.com/us/k/barrier-moisturizers-for-dry-skin",confidence:"High"},
{rank:7,brand:"rhode",product:"Barrier Butter",platform:"TikTok Shop",price:23,size:5,ppo:4.6,velocity:"7.8K sold",signal:"Celebrity-led barrier desire",micro:false,url:"https://shop.tiktok.com/us/k/barrier-moisturizers-for-dry-skin",confidence:"High"},
{rank:8,brand:"COSRX",product:"Ceramide Skin Barrier Moisturizer",platform:"TikTok Shop",price:18,size:2.7,ppo:6.67,velocity:"7.9K sold; +3.4K vs W01",signal:"Ceramide/cholesterol/fatty acid",micro:false,url:"https://shop.tiktok.com/us/pdp/moisturizer-cosrx-the-ceramide-skin-barrier-80ml-for-sensitive-dry-skin/1730843567728136363",confidence:"High"},
{rank:9,brand:"Skinfix",product:"Barrier+ Triple Lipid Peptide",platform:"Cross-platform",price:54,size:1.7,ppo:31.76,velocity:"Prestige benchmark",signal:"3:1:1 lipid story",micro:false,url:"https://skinfix.com/products/barrier-triple-lipid-peptide-cream",confidence:"Medium"},
{rank:10,brand:"AESTURA",product:"Atobarrier 365 Cream",platform:"Cross-platform",price:32,size:2.7,ppo:11.85,velocity:"K-beauty community",signal:"Capsule ceramide system",micro:false,url:"https://www.amazon.com/s?k=AESTURA+Atobarrier+365+Cream",confidence:"Medium"},
{rank:11,brand:"BeautyStat",product:"Universal Pro-Bio Moisture Boost",platform:"Cross-platform",price:50,size:1.7,ppo:29.41,velocity:"Microbiome adjacency",signal:"Probiotic ferment positioning",micro:true,microType:"Probiotic ferment",url:"https://beautystat.com",confidence:"Medium"},
{rank:12,brand:"Gallinée",product:"Hydrating Face Cream",platform:"Cross-platform",price:40,size:1.35,ppo:29.63,velocity:"Microbiome niche",signal:"Prebiotic + postbiotic + lactic acid",micro:true,microType:"Pre/Postbiotic",url:"https://www.gallinee.com/collections/face",confidence:"Medium"},
{rank:13,brand:"TULA",product:"24-7 Hydrating Day & Night Cream",platform:"Cross-platform",price:58,size:1.5,ppo:38.67,velocity:"Probiotic prestige",signal:"Probiotic extracts",micro:true,microType:"Probiotic extract",url:"https://www.tula.com/products/24-7-moisture-hydrating-day-night-cream",confidence:"Medium"},
{rank:14,brand:"Yobee",product:"Probiotic Skin Moisturizing Cream",platform:"TikTok Shop",price:40.13,size:4,ppo:10.03,velocity:"40 sold",signal:"Explicit microbiome support",micro:true,microType:"Probiotic",url:"https://shop.tiktok.com/us/k/skin-probiotics",confidence:"Medium"},
{rank:15,brand:"Mesmerie",product:"Probiome Balance Cream",platform:"TikTok Shop",price:55,size:1.69,ppo:32.54,velocity:"1 sold",signal:"Loud multi-biotic claim; low proof",micro:true,microType:"Pre/Pro/Postbiotic",url:"https://shop.tiktok.com/us/pdp/probiotic-moisturizer-for-sensitive-skin-daily-hydration-care/1731349796933636507",confidence:"Medium"}];
const sets={cleanse,treat,hydrate};
const labels={cleanse:{n:"01",title:"Cleanse",sub:"Remove without stripping",unit:"$ / fl oz"},treat:{n:"02",title:"Treat",sub:"Intervene with a serum",unit:"$ / fl oz"},hydrate:{n:"03",title:"Hydrate",sub:"Replenish and seal",unit:"$ / fl oz"}};
export default function Home(){const[step,setStep]=useState<Step>("cleanse");const[q,setQ]=useState("");const[microOnly,setMicroOnly]=useState(false);const[sort,setSort]=useState("rank");const data=sets[step];const rows=useMemo(()=>data.filter(p=>(!microOnly||p.micro)&&(p.brand+" "+p.product).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="ppo"?a.ppo-b.ppo:sort==="bsr"?(a.bsr??999999)-(b.bsr??999999):a.rank-b.rank),[data,q,microOnly,sort]);const sorted=[...data].sort((a,b)=>a.ppo-b.ppo);const med=sorted[7].ppo;const microCount=data.filter(p=>p.micro).length;const priceRange=`$${sorted[0].ppo.toFixed(2)}–$${sorted[sorted.length-1].ppo.toFixed(2)}`;return <main>
<header className="hero"><nav><span className="mark"/><b>superbiome</b><span className="cobrand">× <img src="/hm-studio-logo.png" alt="HM Studio"/><span>HM Studio</span></span><span className="date">WEEK 02 · JUL 21, 2026</span></nav><div className="heroGrid"><div><p className="eyebrow">BARRIER + MICROBIOME MARKET INTELLIGENCE</p><h1>Barrier repair has become<br/>the price of entry.</h1><p className="dek"><b>Currently,</b> volume is concentrating around legible value anchors while microbiome language is spreading into premium treatments and post-procedure recovery. The opening is no longer to say “biome”—it is to prove why the biology produces a better result.</p></div><div className="heroMetric"><span>State of the union</span><strong>45 SKUs</strong><small>3 steps · 15 priority products each</small></div></div></header>
<section className="stepPicker"><div className="stepPickerIntro"><p className="eyebrow">EXPLORE THE REPORT</p><h2>View this week in</h2><span>Select a step to update every chart, metric and ranking below.</span></div><div className="systemNav" role="tablist" aria-label="View this week's category intelligence">{(Object.keys(labels) as Step[]).map(k=><button key={k} role="tab" aria-selected={step===k} className={step===k?"active":"attention"} onClick={()=>setStep(k)}><span>{labels[k].n}</span><b>{labels[k].title}</b><small>{labels[k].sub}</small><i aria-hidden="true">View step →</i></button>)}</div></section>
<section className="metrics"><div><span>15</span><p>{labels[step].title} SKUs</p></div><div><span>${med.toFixed(2)}</span><p>median / fl oz</p></div><div><span>{microCount}</span><p>microbiome-adjacent</p></div><div><span>{priceRange}</span><p>observed $ / fl oz range</p></div></section>
<section className="section narrative"><div><p className="eyebrow">{labels[step].title.toUpperCase()} STEP · CATEGORY READ</p><h2>{step==="cleanse"?"Mass trust strengthened—even as price rose.":step==="treat"?"Biome language is earning attention, not automatic proof.":"K-beauty is converting barrier literacy into velocity."}</h2></div><div className="readout">{step==="cleanse"?<><p><b>CeraVe and Vanicream improved to Beauty BSR #37 and #29.</b> CeraVe did so while its observed price rose 11%, suggesting trust can absorb modest price pressure.</p><p><b>The prebiotic exception did not share the lift.</b> La Roche-Posay moved from #87 to #134, reinforcing that biome adjacency alone is not the purchase driver.</p></>:step==="treat"?<><p><b>Murad’s $71 biome-balancing serum now shows 1.2K TikTok Shop sales.</b> The premium is supported by a familiar acne job—not microbiome language in isolation.</p><p><b>The watchlist is widening into mists and post-procedure recovery.</b> Format and use occasion may be becoming more differentiating than another generic barrier serum.</p></>:<><p><b>COSRX accelerated from 4.5K to 7.9K visible TikTok Shop sales.</b> A clear ceramide–cholesterol–fatty-acid story is beating louder microbiome claims on observed volume.</p><p><b>New biome products are entering through recovery occasions.</b> PURCELL’s “after laser” framing makes the need concrete, though evidence and scale remain early.</p></>}</div></section>
<section className="section chartSection"><div className="sectionHead"><div><p className="eyebrow">PRICE ARCHITECTURE</p><h2>{labels[step].title} price per ounce</h2></div><div className="microLegend"><span className="microDot"/> Microbiome-adjacent claim</div></div><div className="chart">{sorted.map(p=><div className="barRow" key={p.brand+p.product}><span>{p.brand}{p.micro&&<i className="microDot"/>}</span><div className="track"><div className={`bar ${p.micro?"microbar":""}`} style={{width:`${Math.max(2,p.ppo/Math.max(...data.map(x=>x.ppo))*100)}%`}}/><em style={{left:`${Math.min(91,p.ppo/Math.max(...data.map(x=>x.ppo))*100)}%`}}>${p.ppo.toFixed(2)}</em></div></div>)}</div></section>
<section className="section"><div className="sectionHead"><div><p className="eyebrow">COMPETITIVE SET</p><h2>{labels[step].title} priority set</h2></div><span className="methodTag">Week 02 · checked Jul 22</span></div><div className="controls"><input aria-label="Search" placeholder="Search brand or SKU" value={q} onChange={e=>setQ(e.target.value)}/><label className="check"><input type="checkbox" checked={microOnly} onChange={e=>setMicroOnly(e.target.checked)}/> Microbiome-adjacent only</label><select value={sort} onChange={e=>setSort(e.target.value)}><option value="rank">Sort: trend score</option><option value="ppo">Sort: price / oz</option><option value="bsr">Sort: Amazon BSR</option></select></div><div className="tableWrap"><table><thead><tr><th>#</th><th>Brand / SKU</th><th>Platform</th><th>Price</th><th>Size</th><th>$/oz</th><th>Biome signal</th><th>Velocity / BSR</th></tr></thead><tbody>{rows.map(p=><tr key={p.rank}><td>{p.rank}</td><td><a href={p.url} target="_blank" rel="noreferrer"><b>{p.brand}</b><small>{p.product}</small></a></td><td><span className="pill">{p.platform}</span></td><td>${p.price.toFixed(2)}</td><td>{p.size} oz</td><td><b>${p.ppo.toFixed(2)}</b></td><td>{p.micro?<span className="microPill">{p.microType}</span>:<span className="na">None explicit</span>}<small>{p.signal}</small></td><td>{p.bsr&&<b>BSR #{p.bsr.toLocaleString()}</b>}<small>{p.velocity}</small><span className={`confidence ${p.confidence.toLowerCase()}`}>{p.confidence}</span></td></tr>)}</tbody></table></div></section>
<section className="section signalSection"><div className="weeklyLabel"><p className="eyebrow">WEEKLY UNION</p><span>Week-over-week movement uses comparable public listings only</span></div><h2>What the full system says</h2><div className="signalGrid"><article><span>01</span><p className="eyebrow">CATEGORY</p><h3>Barrier is table stakes—not differentiation.</h3><p>The winning stories now connect repair to a specific ingredient system, occasion or felt result.</p></article><article><span>02</span><p className="eyebrow">VELOCITY</p><h3>Trust absorbed price pressure.</h3><p>CeraVe rose 13 Beauty BSR positions while its observed price increased 11%; Vanicream also strengthened.</p></article><article><span>03</span><p className="eyebrow">MICROBIOME</p><h3>The vocabulary is spreading sideways.</h3><p>New visibility in mists, overnight masks and post-laser creams suggests format and occasion expansion—not yet category proof.</p></article><article><span>04</span><p className="eyebrow">SUPERBIOME</p><h3>Make mechanism the differentiator.</h3><p>The opportunity is to explain what changes, how it is measured and why the customer should feel the difference.</p></article></div></section>
<section className="section signalSection"><div className="weeklyLabel"><p className="eyebrow">WEEK 02 WATCHLIST</p><span>Visible but not yet strong enough to displace the priority set</span></div><h2>Microbiome adjacency is moving into recovery occasions</h2><div className="signalGrid"><article><span>01</span><p className="eyebrow">POST-PROCEDURE</p><h3>PURCELL PIXCELL BIOM</h3><p><a href="https://shop.tiktok.com/us/pdp/purcell-pixcell-biom-after-laser-rebooting-cream-50ml/1732274285196055212" target="_blank" rel="noreferrer">After Laser Rebooting Cream</a> shows 64 sales: early, but the use occasion is unusually legible.</p></article><article><span>02</span><p className="eyebrow">MIST</p><h3>Allies of Skin</h3><p><a href="https://shop.tiktok.com/us/pdp/molecular-saviour-mist-by-allies-of-skin-niacinamide-probiotics-hydrating-spray-for-glowing-skin/1731000766450733685" target="_blank" rel="noreferrer">Molecular Saviour Mist</a> shows 178 sales, pairing probiotics with a portable hydration format.</p></article><article><span>03</span><p className="eyebrow">OVERNIGHT</p><h3>Abib Rice Probiotics</h3><p><a href="https://shop.tiktok.com/us/pdp/abib-rice-probiotic-overnight-mask-nourishes-strengthens-skin-barrier/1731867792772665440" target="_blank" rel="noreferrer">Barrier Jelly mask</a> extends probiotic language into sleep and recovery; scale is not yet validated.</p></article><article><span>04</span><p className="eyebrow">READ</p><h3>Occasion may beat terminology.</h3><p>“After laser,” “overnight” and “mist” give the biology a job. That is strategically stronger than biome language without a use case.</p></article></div></section>
<section className="section actions"><div><p className="eyebrow">LARRY'S THREE-STEP SYSTEM</p><h2>Less routine.<br/>More reason.</h2></div><ol><li><b>Cleanse without collateral damage.</b><span>Make what the formula preserves as important as what it removes.</span></li><li><b>Treat the measurable need.</b><span>One targeted intervention, with mechanism and evidence separated cleanly.</span></li><li><b>Hydrate to maintain the system.</b><span>Replenish water and lipids; earn repeat purchase through felt results, not dependency.</span></li></ol></section>
<footer><div><b>Methodology</b><p>Composite trend set based on live Amazon BSR/velocity where exposed, TikTok Shop product-level sold/review signals, Sephora and Ulta bestseller/review movement, Google Trends search direction, TikTok Creative Center momentum, verified launch pages, and corroborating editorial/community visibility. Week-over-week claims require the same observable listing and metric; non-comparable shop-level totals are labeled separately. Commerce signals carry the most weight; editorial or community chatter cannot independently earn a top-15 rank. Microbiome-adjacent includes explicit microbiome, biome, prebiotic, probiotic, postbiotic, ferment or flora language. Inclusion is not validation. No unavailable BSR was inferred. Week 02 is dated to the scheduled Jul 21 run and was recovered/checked Jul 22 after an automation failure.</p></div><div><b>Next refresh</b><p>Tuesday, Jul 28 · 9:00 AM ET<br/>All rankings, hero readout, weekly union and strategic implications</p></div><div className="studioCredit"><img src="/hm-studio-logo.png" alt="HM Studio logo"/><p><b>Strategy &amp; analysis by HM Studio</b><br/>Fractional Brand &amp; GTM Architecture<br/><a href="https://hannahmcgough.com" target="_blank" rel="noreferrer">hannahmcgough.com</a><br/><small>© 2026 HM Studio</small></p></div></footer></main>}
